// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBookStore.Data;

#nullable disable

namespace OnlineBookStore.Migrations
{
    [DbContext(typeof(OnlineBookStoreContext))]
    [Migration("20251213040643_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineBookStore.Domain.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7380),
                            DateUpdated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7380),
                            Name = "M. Shwe",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7382),
                            DateUpdated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7382),
                            Name = "A. Tan",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7384),
                            DateUpdated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7384),
                            Name = "K. Lim",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQty")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7205),
                            DateUpdated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7206),
                            Description = "A cozy fiction story set in a hidden bookstore.",
                            ISBN = "978-1111111111",
                            Price = 18.90m,
                            StockQty = 10,
                            Title = "The Silent Shelf",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7212),
                            DateUpdated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7213),
                            Description = "Understanding patterns in real-world datasets.",
                            ISBN = "978-2222222222",
                            Price = 22.50m,
                            StockQty = 5,
                            Title = "Data in the City",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7215),
                            DateUpdated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7215),
                            Description = "A practical guide to Blazor development.",
                            ISBN = "978-3333333333",
                            Price = 28.00m,
                            StockQty = 7,
                            Title = "C# for Busy Students",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Fiction",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7443),
                            DateUpdated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7444),
                            Description = "Novels and stories (literary, romance, mystery, fantasy).",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Non-Fiction",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7446),
                            DateUpdated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7446),
                            Description = "Real-world topics (biography, business, self-help, history).",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Education",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7448),
                            DateUpdated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7448),
                            Description = "Learning materials (programming, textbooks, exam guides).",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tampines, Singapore",
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7541),
                            Email = "john.tan@email.com",
                            FullName = "John Tan",
                            Phone = "91234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Jurong East, Singapore",
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7542),
                            Email = "sarah.lim@email.com",
                            FullName = "Sarah Lim",
                            Phone = "98765432"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Woodlands, Singapore",
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7544),
                            Email = "daniel.wong@email.com",
                            FullName = "Daniel Wong",
                            Phone = "90112233"
                        });
                });

            modelBuilder.Entity("OnlineBookStore.Domain.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7700),
                            LineTotal = 18.90m,
                            OrderId = 1,
                            Quantity = 1,
                            UnitPrice = 18.90m
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7702),
                            LineTotal = 22.50m,
                            OrderId = 1,
                            Quantity = 1,
                            UnitPrice = 22.50m
                        });
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7622),
                            OrderDate = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7620),
                            Status = "Completed",
                            TotalAmount = 41.40m
                        });
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 41.40m,
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7767),
                            DatePaid = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7766),
                            OrderId = 1,
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Paid"
                        });
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            Comment = "Excellent book!",
                            CustomerId = 1,
                            DateCreated = new DateTime(2025, 12, 13, 12, 6, 43, 222, DateTimeKind.Local).AddTicks(7844),
                            Rating = 5
                        });
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Book", b =>
                {
                    b.HasOne("OnlineBookStore.Domain.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookStore.Domain.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineBookStore.Domain.OrderItem", b =>
                {
                    b.HasOne("OnlineBookStore.Domain.Book", "Book")
                        .WithMany("OrderItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookStore.Domain.Orders", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Orders", b =>
                {
                    b.HasOne("OnlineBookStore.Domain.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Payment", b =>
                {
                    b.HasOne("OnlineBookStore.Domain.Orders", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("OnlineBookStore.Domain.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Review", b =>
                {
                    b.HasOne("OnlineBookStore.Domain.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineBookStore.Domain.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Book", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("OnlineBookStore.Domain.Orders", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
